spring:
  application:
    name: LostFound-Service
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true



jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer